### ISSUE TITLE
psm$new output !

### ISSUE THREAD

**Issue by MattheneusHTA** [InnovationValueInitiative/hesim#6]
In my survival models I include several variables: 
flexsurvreg(Surv(endpoint3_time, endpoint3_status) ~ ostprof + PSADT + patient_id +
                                factor(strategy_id),
                              data = surv_est_data,
                              dist = "weibull")

However in the psm$new output only the patient_id variable is included. How do I get the psm$new to correspond the to my survival models ?

Clarification: In the psm$survival_ only strategy_id and patient_id are included.  but I have more variables in my model than that?

**Comment by dincerti** [comment]
This is the expected behavior. The model simulates outcomes for each patient_id and strategy_id combination as a function of the covariates in your model.
